pipeline {
    agent any

    environment {
        ECR_REGISTRY = "992382545251.dkr.ecr.us-east-1.amazonaws.com"
        REPO_NAME    = "amit-flask-app"
        IMAGE_TAG    = "latest"
        ECR_TOKEN    = "eyJwYXlsb2FkIjoiZlVPQ2tjeU9CSmRyUkRQanE4UUVuMlRUNjI5TEI0NE12ZlFVYzVCRkNGUzJ4d0RlRlcwNmo4VVBQQU5VS3ZaUFBzeTczTEhLZC90UUh3Zng3YnQvV205SHR5bk96Y3NPMHlyV282M0RSb1dCV0gvZUs4bXlraVh0dEh4WmNJaVdHZnJjdkVaR1Vod3AvRVJ4aDdNZjd5dEZEV0VDaHRoVU5YM1paRnQyZGwyR3VMZlBmSWNpMjB0QlFWVWZlb0FsOWpUWjdOYzFEOHRFV3BBNFZRbnl5RnVZYThtS2lrLzdZeDBnM3dwYjVLbjd0R3oyakFPMmkwM0hEblNzWVV1VDFMMW1yRFlWdUFIbm5oSE5yWXpaN3doYTZ2V2xzbUprK2UzdVlaQTF6SkZPaDZ3UWNiajNrTnVLWTE3b0J3OFZaWFI3aExHU1JzazhxRFhmRU1NZ0xoQmtITkhya0lHc3BGaWlPbDBmbEpRNlIwM29TNER4S1FWS1hsdWsvTWNzL1JPcTgrYkprem1SdnlueWc0L0hOMUpzTzZEQWxuRlVpU0tDSUdaWWNudEhkdDFKRURPVFBlMjNCUWQ3OTNIQTlXR2luZ3FFemJyT1dDTzgrZ2RMdU80Z3k4Z3JhblRmR0NVTGVnUWpuS1lWM1YvOENpM2ptUURwZVBoU3prM1FjeldQRk42RUNkL1VKYUFLMWlqc0o2aEJtbXBPOTJnbHlYSU1BQmYwN1ZDNUl6YTNlQXZZWG1xT1JkcUI1S2pDaE8rYU1aRGk5SmNYYTd0SDZGRlZmSGZzK1BvZVhVbVI4Z3B6Zzk3ajhTVi9XS3REcGhYTTFZZGpFbGlNL0g3U1JqY0NlQ0VKSFA0MFowaHJ0ZVVaSWUrK2FYd1Q5Rjk5NUliRjViTEtkUGtrT2Y3S3FnTkl2TkVDejZWL3dtWHdZbXYrMW1oWGlKZEkzb0tFdGpURngzOHpmMUdQcGdubi93WjVLbW1qTXFQaE44UndCd0VLY1NweXFxL25acm9WSmVNU3o5S2hHSk5zOWdleThRNG41c280M0R1cm9kbFN4MWxCZTZKNWR2Z0NwT3hBOUd1enA5RTlLY3l5UHBweTJ0TUNRcHRDbURlSGkzcWVmRWhuaCtOeG4xM2tzTHA0cmdZTHNjTHhDN25lUTc2TXJQUnZkdmpWdkNzM0c4NnZNbnIvVFkwVTVqcWNQTjc2NE9Ibm9FT2ZQeDNmMzJVZzgyVUMyVy9iUTVubTZuOTQwajQvZGJ6aDFvUmVpWnl4Sk1VS2VNbVd3RGlpY1JWKzNBSVBwakFIOTJvcGd0V0RJNXp5U1h5aUNJSVNBRlNzazJFd2RjMm5aaXZiK1RVbzJZb2VTYjh6UC9KYWVoM0J2Rmw4TTF4YzErVzJZMTM0KzN4aU1FWFVTaGhVanByeTBFMHdnRDBtZ2hyZXEycnlVcnltWUE1ZWREN1hPM0gydzJxVGtvNjAyMGtKamVJdFFQalRjZFhvQkV0VFVYZzBiRU9kemJuVTh4emxzcWEwZFFhQU9MY3MrQm1GZzR0MDMySm9nNWdtWThBcU1pcHcxV0RPRy9EczZBMW1lbkNTc1IzaXR2NUJSRkgxNEJ0WncyU2hOMUtqUlQzdDROTUxtTGkrOFJqaExFNTF6Q3JlbXc9PSIsImRhdGFrZXkiOiJBUUVCQUhod20wWWFJU0plUnRKbTVuMUc2dXFlZWtYdW9YWFBlNVVGY2U5UnE4LzE0d0FBQUg0d2ZBWUpLb1pJaHZjTkFRY0dvRzh3YlFJQkFEQm9CZ2txaGtpRzl3MEJCd0V3SGdZSllJWklBV1VEQkFFdU1CRUVEQTdxSFRNNGdrRTZrNU96OFFJQkVJQTdRRENqWERLT3d6eFNTVEJDWHc3aEI2U044MllWNGtUS29rL2ZsSUY1bDdwTlVoNURsVjRXcVF5bjgwL0MwMmIvTTkxSkRqMzFNMnkxWEJrPSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTc4MzI5MjIxN30="
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${REPO_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push to AWS ECR') {
            steps {
                script {
                    sh "echo '${ECR_TOKEN}' | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
                    sh "docker tag ${REPO_NAME}:${IMAGE_TAG} ${ECR_REGISTRY}/${REPO_NAME}:${IMAGE_TAG}"
                    sh "docker push ${ECR_REGISTRY}/${REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }
}
